<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Mutagen.Bethesda.Analyzers.Tests</RootNamespace>
        <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Mutagen.Bethesda.Skyrim" />
        <PackageReference Include="Mutagen.Bethesda.Testing" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mutagen.Bethesda.Analyzers\Mutagen.Bethesda.Analyzers.csproj" />
      <ProjectReference Include="..\Mutagen.Bethesda.Analyzers.Engine\Mutagen.Bethesda.Analyzers.Engine.csproj" />
      <ProjectReference Include="..\Mutagen.Bethesda.Analyzers.Skyrim\Mutagen.Bethesda.Analyzers.Skyrim.csproj" />
      <ProjectReference Include="..\Mutagen.Bethesda.Analyzers.Testing\Mutagen.Bethesda.Analyzers.Testing.csproj" />
    </ItemGroup>

</Project>
