<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <IsPackable>true</IsPackable>
      <PackageId>Mutagen.Bethesda.Analyzers.Engine</PackageId>
      <Description>Core analysis engine with drivers and reporting for Bethesda mod analyzers.</Description>
      <RootNamespace>Mutagen.Bethesda.Analyzers</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mutagen.Bethesda.Analyzers.SDK\Mutagen.Bethesda.Analyzers.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" />
      <PackageReference Include="Mutagen.Bethesda.Autofac" />
      <PackageReference Include="GitVersion.MsBuild">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.SourceLink.GitHub" />
    </ItemGroup>

</Project>
